version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "theme/dependencies"
  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: "weekly"
    labels:
      - "theme/dependencies"
      - "theme/api"
  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: "weekly"
    labels:
      - "theme/dependencies"
      - "theme/ui"
  - package-ecosystem: npm
    directory: "/website"
    schedule:
      interval: "weekly"
    labels:
      - "theme/dependencies"
      - "theme/website"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions"
    schedule:
      interval: "weekly"
    labels:
      - "theme/dependencies"
