#!/bin/bash

mkdir -p /opt/wander/data
chown wander:wander /opt/wander/data
chown -R wander:wander /etc/wander.d

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
