#!/bin/bash

if [ "$1" = "purge" ]; then
  userdel wander
fi

if [ "$1" == "upgrade" ] && [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true
  systemctl restart wander >/dev/null || true
fi

exit 0
