# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/open-wander/wander/discussions
    about: If you have a question, or are looking for advice, please post on our GitHub Discussions.
  - name: Wander Documentation
    url: https://openwander.org/wander/docs
    about: Please check out our documentation for guides and reference material.
